sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
branches:
  only:
    - master
email:
  on_failure: change
  on_success: never
