language: node_js
node_js:
  - 'lts/*'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
script:
  - yarn lint
  - yarn test -- --ci
  - yarn website
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $CONVENTIONAL_GITHUB_RELEASER_TOKEN
  local_dir: examples/dist
  on:
    branch: master
    node: 'lts/*'

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn release
        on:
          branch: master
