
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile --non-interactive
    - run: yarn test -- --ci
  lint:
    name: Lint source code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile --non-interactive
    - name: Lint
      run: yarn lint
  website:
    name: Test build website
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile --non-interactive
    - name: Build website
      run: yarn website
